[2023-01-27 01:30:20,597] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: d1_script.generate_dim scheduled__2023-01-26T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2023-01-27 01:30:20,601] {local_task_job.py:101} INFO - Task is not able to be run
